name: Perform Mixeway Scan

jobs:
mixeway-scan:
name: Mixeway Scanning
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v1
- name: Prepare variables
id: vars
shell: bash
run: |
echo "##[set-output name=branch;]$(echo 
${GITHUB_REF#refs/heads/})"
echo "::set-output name=sha_short::$(git rev-parse HEAD)"
- name: Prepare Mixeway docker image
run: |
docker pull mixeway/scanner:latest
- name: Run Scan
run: |
docker run -e OSS_USERNAME=zbigniew.kaczynski@op.pl -e OSS_KEY=8c31af84e6bb7fc08dd20a7757427605890ee875 -e MIXEWAY_URL=https://hub.mixeway.io -e MIXEWAY_KEY=09a2e15b-df79-4dd1-a644-fdbfd2d237de -e MIXEWAY_PROJECT_ID=61 -e MODE=STANDALONE -e MIXEWAY_PROJECT_NAME=ZKaczynski_lab_secure_app -e COMMIT_ID=test -e BRANCH=master -v /opt/lab_sec_audit/sast:/opt/sources mixeway/scanner:latest

